import Head from 'next/head'
import Image from 'next/image';
import { Gilda_Display } from 'next/font/google'

import Layout from '@/components/Layout';
import styles from '@/styles/pages/about/ContactUs.module.css';

const gilda = Gilda_Display({ weight: '400', subsets: ['latin'] });

export default function ContactUs() {
    return (
        <>
        <Head>
            <title>Front Four Cellars</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={gilda.className}>
            <Layout>
                <section style={{marginTop: '180px'}}>
                    <div style={{ padding: '20px' }}>
                        <h1 style={{ 
                            textAlign: 'center', 
                            fontSize: '60px', 
                            margin: '1rem 0 1.5rem 0', 
                            overflowWrap: 'break-word', 
                            lineHeight: '1.2',
                            fontWeight: '300'
                        }}>Contact Us</h1>
                        <p style={{ 
                            maxWidth: '1100px',
                            margin: '1em auto',
                            lineHeight: '1.5', 
                            letterSpacing: '0.02em', 
                            overflowWrap: 'break-word',
                            textAlign: 'left',
                            fontSize: '22px',
                        }}>
                            The team at Front Four Cellars can best be reached by emailing the specific department:  
                        </p>
                        <div className={styles.emailContainer}>
                            <p style={{ 
                                maxWidth: '1100px',
                                width: '45%',
                                margin: '0',
                                lineHeight: '1.5', 
                                letterSpacing: '0.02em', 
                                overflowWrap: 'break-word',
                                fontSize: '22px',
                            }}>
                                <strong>General Inquiries:</strong>
                                <br/>
                                &#9;<a href="mailto:info@frontfourcellars.com">info@frontfourcellars.com</a>
                            </p>
                            <p style={{ 
                                maxWidth: '1100px',
                                width: '45%',
                                margin: '0',
                                lineHeight: '1.5', 
                                letterSpacing: '0.02em', 
                                overflowWrap: 'break-word',
                                fontSize: '22px',
                            }}>
                                <strong>Technical Support (website issues):</strong>
                                <br/>
                                &#9;<a href="mailto:support@frontfourcellars.com">support@frontfourcellars.com</a>
                            </p>
                            <p style={{ 
                                maxWidth: '1100px',
                                width: '45%',
                                margin: '0',
                                lineHeight: '1.5', 
                                letterSpacing: '0.02em', 
                                overflowWrap: 'break-word',
                                fontSize: '22px',
                            }}>
                                <strong>Wine Club:</strong>
                                <br/>
                                &#9;<a href="mailto:wineclub@frontfourcellars.com">wineclub@frontfourcellars.com</a>
                            </p>
                            <p style={{ 
                                maxWidth: '1100px',
                                width: '45%',
                                margin: '0',
                                lineHeight: '1.5', 
                                letterSpacing: '0.02em', 
                                overflowWrap: 'break-word',
                                fontSize: '22px',
                            }}>
                                <strong>Marketing & Sales:</strong>
                                <br/>
                                &#9;<a href="mailto:busbev@frontfourcellars.com">busbev@frontfourcellars.com</a>
                            </p>
                        </div>
                        <p style={{ 
                            maxWidth: '800px',
                            margin: 'auto',
                            lineHeight: '1.5', 
                            letterSpacing: '0.02em', 
                            overflowWrap: 'break-word',
                            fontSize: '22px',
                            marginTop: '20px'
                        }}>
                            <strong>Employment:</strong>
                            <br/>
                            &#9;<a href="mailto:careers@frontfourcellars.com">careers@frontfourcellars.com</a> 
                        </p>
                        <p style={{ 
                            maxWidth: '1100px',
                            margin: '1em auto',
                            lineHeight: '1.5', 
                            letterSpacing: '0.02em', 
                            overflowWrap: 'break-word',
                            textAlign: 'left',
                            fontSize: '22px',
                        }}>
                            If you have a need to mail &quot;anything&quot; to our team, please use one of the following addresses. Please include a 
                            C/O &quot;Department&quot; for quicker processing.  
                        </p>
                        <section className={styles.addressContainer}>
                            <div style={{  }}>
                                <strong>Corporate Address:</strong>
                                <br/>
                                Front Four Cellars, LC
                                <br/>
                                Box 2931
                                <br/>
                                Glen Allen, Virginia 23058
                            </div>
                            <div style={{  }}>
                                <strong>New Hampshire Location:</strong>
                                <br/>
                                Front Four Cellars of NH
                                <br/>
                                13 Railroad Avenue
                                <br/>
                                Wolfeboro, NH 03894
                            </div>
                        </section>
                        <p style={{ 
                            maxWidth: '1100px',
                            margin: '1.5em auto',
                            lineHeight: '1.5', 
                            letterSpacing: '0.02em', 
                            overflowWrap: 'break-word',
                            textAlign: 'left',
                            fontSize: '22px',
                        }}>
                            We value your input. If you have taken the time to visit our website or tasting room(s) and find we can provide 
                            better quality service, we want to hear from you. No issue is too small when it comes to our customers. We want to be the best we can be.  
                        </p>
                        <p style={{ 
                            maxWidth: '1100px',
                            margin: '1.5em auto',
                            lineHeight: '1.5', 
                            letterSpacing: '0.02em', 
                            overflowWrap: 'break-word',
                            fontSize: '22px',
                        }}>
                            <strong>Holiday Schedule:</strong>
                            <br />
                            We will be observing the falling holidays and providing our great team with some family time. We will be closed on the following holidays. 
                            <ul>
                                <li>New Year&apos;s Day - (New Year&apos;s Eve YES)</li>
                                <li>Easter Day</li>
                                <li>Thanksgiving Day</li>
                                <li>Christmas Day - (Christmas Eve open till 4p)</li>
                            </ul>
                            <em><strong>
                                A special note: We will not be opening on Sundays before 1p and will always be closing at 6p as we want families to attend church and 
                                hopefully a lunch together before heading out for the day and then finishing the Lord&apos;s Day with dinner together.  
                            </strong></em> 
                        </p>
                    </div>
                </section>
            </Layout>
        </main>
        </>
    );
}
