import Head from 'next/head'
import Image from 'next/image';
import { Gilda_Display } from 'next/font/google'

import Layout from '@/components/Layout';
import styles from '@/styles/pages/about/Story.module.css';

const gilda = Gilda_Display({ weight: '400', subsets: ['latin'] });

/*
    
                    <div style={{ width: '100%', aspectRatio: '16/9', position: 'relative', marginBottom: '6vh' }}>
                        <Image src='/placeholder.jpg' alt="image" fill />
                    </div>
*/

export default function Story() {
    return (
        <>
        <Head>
            <title>Front Four Cellars</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={gilda.className}>
            <Layout>
                <section className={styles.container}>
                    <div className={styles.imageContainer}>
                        <Image src="/About/ourstory.png" alt="humble beginning" fill />
                    </div>
                    <div>
                        <h1 style={{ 
                            textAlign: 'center', 
                            fontSize: '60px', 
                            margin: '1rem 0 1.5rem 0', 
                            overflowWrap: 'break-word', 
                            lineHeight: '1.2',
                            fontWeight: '300'
                        }}>Our Story</h1>
                        <p style={{ 
                            maxWidth: '1100px',
                            margin: '1.5em auto',
                            lineHeight: '1.5', 
                            letterSpacing: '0.02em', 
                            overflowWrap: 'break-word',
                            textAlign: 'center',
                            fontSize: '22px',
                        }}>
                            Front Four Cellars is the result of a passion for wine that began years ago.  In 2017, wine lovers and entrepreneurs, Julia and Michael, 
                            decided to try their hand at making wine in their garage.  Julia, a teacher, and Michael, a business owner, set out to make exceptional 
                            craft wine that was distinctive in both flavor and quality. By combining high quality natural ingredients with exceptional wines, they feel 
                            they met their goal.  Fast-forward to 2022, and these wine connoisseurs and former hobbyists decided 
                            their wines are unique enough to stand out in the market.  We hope you agree! 
                        </p>
                    </div>
                    <div className={styles.imageContainer}>
                        <Image src="/About/ourstory.png" alt="humble beginning" fill />
                    </div>
                </section>
            </Layout>
        </main>
        </>
    );
}