import Head from 'next/head'
import Image from 'next/image';
import { Gilda_Display } from 'next/font/google'

import Layout from '@/components/Layout';
import styles from '@/styles/pages/about/Team.module.css';

const gilda = Gilda_Display({ weight: '400', subsets: ['latin'] });


export default function Team() {
    return (
        <>
        <Head>
            <title>Front Four Cellars</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={gilda.className}>
            <Layout>
                <section style={{ width: '90%', margin: '0 auto', position: 'relative' }}>
                    <h1 style={{ 
                        textAlign: 'center', 
                        fontSize: '60px', 
                        margin: '1rem 0 1.5rem 0', 
                        overflowWrap: 'break-word', 
                        lineHeight: '1.2',
                        fontWeight: '300'
                    }}>Meet the Team</h1>
                    <p style={{ 
                        maxWidth: '1000px',
                        margin: '1.5em auto',
                        lineHeight: '1.5', 
                        letterSpacing: '0.02em', 
                        overflowWrap: 'break-word',
                        textAlign: 'center',
                        fontSize: '22px',
                    }}>
                        Our team&apos;s dedication and drive are essential to the purpose of what we do here at Front Four Cellars. From delicious wines, to the service we provide 
                        our customer, we can&apos;t express how invaluable our FFC Family is to the success of our company. 
                    </p>
                    <div className={styles.teamContainer}>
                        <div>
                            <div className={styles.titleContainer}>Julia - Owner / Chief People Person</div>
                            <div className={styles.imageContainer}>
                                <Image src="/About/julie.png" alt="Julia" fill />
                            </div>
                        </div>
                        <div>
                            <div className={styles.titleContainer}>Michael - Winemaker Wannabe / Operations</div>
                            <div className={styles.imageContainer}>
                                <Image src="/About/michael.png" alt="Michael" fill />
                            </div>
                        </div>
                        <div>
                            <div className={styles.titleContainer}>Ranger - The Main Attraction</div>
                            <div className={styles.imageContainer}>
                                <Image src="/About/doggo.png" alt="Ranger" fill />
                            </div>
                        </div>
                    </div>
                    <div className={styles.teamContainer}>
                        <div>
                            <div className={styles.titleContainer}>Winemakers / Consultants: Nathan & Rachel</div>
                            <div className={styles.imageContainer}>
                                <Image src="/placeholder.jpg" alt="Julia" fill />
                            </div>
                        </div>
                        <div>
                            <div className={styles.titleContainer}>Winemaker Emeritus: Dean</div>
                            <div className={styles.imageContainer}>
                                <Image src="/placeholder.jpg" alt="Julia" fill />
                            </div>
                        </div>
                        <div>
                            <div className={styles.titleContainer}>Shipping Coordinator: Ethan</div>
                            <div className={styles.imageContainer}>
                                <Image src="/About/ethan.jpg" alt="Ethan" fill />
                            </div>
                        </div>
                    </div>
                </section>
            </Layout>
        </main>
        </>
    );
}